CompanyFleetManagerWebMvc/Controllers/EmployeesController.cs
using CompanyFleetManager;
using CompanyFleetManager.Models.Entities;
using CompanyFleetManagerWebApp.Services;
using CompanyFleetManagerWebMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CompanyFleetManagerWebApp.Controllers
{
    public class EmployeesController : Controller
    {
        WebServiceFleetApi WebService;

        public EmployeesController(WebServiceFleetApi webService)
        {
            WebService = webService;
        }
        public async Task<IActionResult> Index()
        {
            var employees = await WebService.FetchEmployees();
            return View(employees);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                await WebService.AddEmployee(employee);

                return RedirectToAction("Index");
            }

            return View("Error", new ErrorViewModel() { DetailedMessage = $"Model state is not valid! Following entries are invalid: {Utils.GetNamesOfNonValidEntries(ModelState)}" });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var employees = await WebService.FetchEmployees();
            var employee = employees.FirstOrDefault(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            return View(employee);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employees = await WebService.FetchEmployees();
            var employee = employees.Find(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            await WebService.RemoveEmployee(employee);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var employees = await WebService.FetchEmployees();
            var employee =  employees.FirstOrDefault(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            return View(employee);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditConfirmed(int id, Employee employee)
        {
            if (ModelState.IsValid)
            {
                await WebService.UpdateEmployee(employee);

                return RedirectToAction("Index");
            }

            return View("Error", new ErrorViewModel() { DetailedMessage = $"Model state is not valid! Following entries are invalid: {Utils.GetNamesOfNonValidEntries(ModelState)}" });
        }

        public async Task<IActionResult> Details(int id)
        {
            var employees = await WebService.FetchEmployees();
            var employee = employees.Find(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            return View(employee);
        }

    }
}

CompanyFleetManagerWebMvc/Controllers/RentalsController.cs
using CompanyFleetManager;
using CompanyFleetManager.Models.Entities;
using CompanyFleetManagerWebApp.Services;
using CompanyFleetManagerWebApp.ViewModels;
using CompanyFleetManagerWebMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace CompanyFleetManagerWebApp.Controllers
{
    public class RentalsController : Controller
    {
        WebServiceFleetApi WebService;

        public RentalsController(WebServiceFleetApi webService)
        {
            WebService = webService;
        }

        public async Task<IActionResult> Index()
        {
            var rentals = await WebService.FetchRentals();
            var employees = await WebService.FetchEmployees();
            var vehicles = await WebService.FetchVehicles();

            List<RentalViewModel> rentalViewModels = new List<RentalViewModel>();
            foreach (var rental in rentals)
            {
                var employee = employees.Find(x => x.EmployeeId == rental.RentingEmployeeId);
                var vehicle = vehicles.Find(x => x.VehicleId == rental.RentedVehicleId);

                rentalViewModels.Add(new RentalViewModel(rental, new ShortenedEmployeeData(employee), new ShortenedVehicleData(vehicle)));
            }

            return View(rentalViewModels);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Employees = await WebService.FetchEmployees();
            ViewBag.Vehicles = await WebService.FetchVehicles();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Rental rental)
        {
            rental.RentedVehicle = (await WebService.FetchVehicles()).FirstOrDefault(v => v.VehicleId == rental.RentedVehicleId);
            rental.RentingEmployee = (await WebService.FetchEmployees()).FirstOrDefault(e => e.EmployeeId == rental.RentingEmployeeId);

            ModelState.Remove("RentedVehicle");
            ModelState.Remove("RentingEmployee");

            if (rental.RentedVehicle == null || rental.RentingEmployee == null)
            {
                return View("Error", new ErrorViewModel() { DetailedMessage = "Invalid Vehicle or Employee selection!" });
            }

            if (ModelState.IsValid)
            {
                await WebService.AddRental(rental);

                return RedirectToAction("Index");
            }

            return View("Error", new ErrorViewModel() { DetailedMessage = $"Model state is not valid! Following entries are invalid: {Utils.GetNamesOfNonValidEntries(ModelState)}" });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var rentals = await WebService.FetchRentals();
            var rental = rentals.FirstOrDefault(r => r.RentalId == id);

            if (rental == null)
                return NotFound();

            return View(rental);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rentals = await WebService.FetchRentals();
            var rental = rentals.Find(r => r.RentalId == id);

            if (rental == null)
                return NotFound();

            await WebService.RemoveRental(rental);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var rentals = await WebService.FetchRentals();
            var rental = rentals.FirstOrDefault(r => r.RentalId == id);

            if (rental == null)
                return NotFound();

            return View(rental);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditConfirmed(int id, Rental rental)
        {
            if (ModelState.IsValid)
            {
                await WebService.UpdateRental(rental);

                return RedirectToAction("Index");
            }

            return View("Error", new ErrorViewModel() { DetailedMessage = $"Model state is not valid! Following entries are invalid: {Utils.GetNamesOfNonValidEntries(ModelState)}" });
        }

        public async Task<IActionResult> Details(int id)
        {
            var rentals = await WebService.FetchRentals();
            var rental = rentals.Find(r => r.RentalId == id);

            if (rental == null)
                return NotFound();

            return View(rental);
        }
    }
}

CompanyFleetManagerWebMvc/Controllers/VehiclesController.cs
using CompanyFleetManager;
using CompanyFleetManager.Models.Entities;
using CompanyFleetManagerWebApp.Services;
using CompanyFleetManagerWebMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace CompanyFleetManagerWebApp.Controllers
{
    public class VehiclesController : Controller
    {
        WebServiceFleetApi WebService;

        public VehiclesController(WebServiceFleetApi webService)
        {
            WebService = webService;
        }

        public async Task<IActionResult> Index()
        {
            var vehicles = await WebService.FetchVehicles();
            return View(vehicles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Vehicle vehicle) //submit button pressed
        {
            if (ModelState.IsValid)
            {
                await WebService.AddVehicle(vehicle);

                return RedirectToAction("Index");
            }

            return View("Error", new ErrorViewModel() { DetailedMessage = $"Model state is not valid! Following entries are invalid: {Utils.GetNamesOfNonValidEntries(ModelState)}" });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var vehicles = await WebService.FetchVehicles();
            var vehicle = vehicles.FirstOrDefault(v => v.VehicleId == id);

            if (vehicle == null)
                return NotFound();

            return View(vehicle);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicles = await WebService.FetchVehicles();
            var vehicle = vehicles.Find(v => v.VehicleId == id);

            if (vehicle == null)
                return NotFound();

            await WebService.RemoveVehicle(vehicle);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var vehicles = await WebService.FetchVehicles();
            var vehicle = vehicles.FirstOrDefault(v => v.VehicleId == id);

            if (vehicle == null)
                return NotFound();

            return View(vehicle);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditConfirmed(int id, Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                await WebService.UpdateVehicle(vehicle);

                return RedirectToAction("Index");
            }

            return View("Error", new ErrorViewModel() { DetailedMessage = $"Model state is not valid! Following entries are invalid: {Utils.GetNamesOfNonValidEntries(ModelState)}" });
        }

        public async Task<IActionResult> Details(int id)
        {
            var vehicles = await WebService.FetchVehicles();
            var vehicle = vehicles.Find(v => v.VehicleId == id);

            if (vehicle == null)
                return NotFound();

            return View(vehicle);
        }
    }
}

CompanyFleetManagerWebMvc/Views/Shared/_EmployeeSelect.cshtml
@using CompanyFleetManager.Models.Entities
@model Rental

<div>
    <label>Employee</label> 
    <br />
    <select id="selectEmployee" asp-for="RentingEmployeeId" class="form-control">
        @foreach(var employee in ViewBag.Employees as List<Employee>)
        {
            <option value="@employee.EmployeeId">@employee.Forename @employee.Middlename @employee.Surname</option>
        }
    </select>
</div>

CompanyFleetManagerWebMvc/Views/Shared/_Layout.cshtml
@inject CompanyFleetManagerWebApp.Models.UserLoggedState UserState

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyFleetManager</title>
    <link rel="stylesheet" href="~/css/darkly.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toast.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CompanyFleetManagerWebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CompanyFleetManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a id="PageIndex" class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="PagePrivacy" class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a id="PageUtils" class="nav-link" asp-area="" asp-controller="Home" asp-action="Utils">Utils</a>
                        </li>
                        <li class="nav-item">
                            <a id="PageRentals" class="nav-link" asp-area="" asp-controller="Rentals" asp-action="Index">Rentals</a>
                        </li>
                        <li class="nav-item">
                            <a id="PageVehicles" class="nav-link" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a id="PageEmployees" class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        @if (UserState.IsUserLogged)
                        {
                            <li class=" nav-item" style="margin-top: 8px;">
                                <span class="navbar-text">
                                    Logged in as: @UserState.LoggedUserEmail
                                </span>
                            </li>
                            <li class=" nav-item" style="margin-left: 10px;">
                                <a class="btn btn-primary" href="/Identity/Account/Logout">Log out</a>
                            </li>
                        }
                        else
                        {
                            <li class=" nav-item">
                                <a class="btn btn-primary" href="/Identity/Account/Login">Log in</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="toast"></div>
        <div class="toast toast_success"></div>
        <div class="toast toast_warning"></div>
        <div class="toast toast_error"></div>
        <div class="container">
            &copy; 2024 - CompanyFleetManagerWebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toast.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CompanyFleetManagerWebMvc/Views/Shared/_VehicleSelect.cshtml
@using CompanyFleetManager.Models.Entities
@model Rental

<div>
    <label>Vehicle</label>
    <br />
    <select id="selectVehicle" asp-for="RentedVehicleId" class="form-control">
        @foreach(var vehicle in ViewBag.Vehicles as List<Vehicle>)
        {
            <option asp-for="RentedVehicleId" value="@vehicle.VehicleId">@vehicle.Brand @vehicle.Model, @vehicle.LicencePlateNumber</option>
        }
    </select>
</div>